### ISSUE TITLE
Build All Examples 

### ISSUE THREAD

**Issue by cbsistem** [tedchoward/ThinWire#7]
Hello

I build all examples:

http://localhost:8080/SimpleApp/                    excuted in chrome     v1.2_RC1_r394
http://localhost:8080/thinwire-playground/      excuted in chrome    v1.2_RC2
http://localhost:8080/thinwire-mail/                 excuted in chrome    v1.2_RC2

http://localhost:8080/thinwire-formcreator/     error  in chrome    v1.2_RC2

    INFORMAÇÕES: Loading ThinWire(R) RIA Ajax Framework v1.2_RC2
jan 19, 2017 2:41:40 AM thinwire.apps.formcreator.ProjectSheet$1 propertyChange
INFORMAÇÕES: user object is null for item:Loading...
jan 19, 2017 2:41:40 AM thinwire.ui.Application reportException
GRAVE: null
java.lang.NullPointerException
	at thinwire.apps.formcreator.PropertySheet.setActiveObject(PropertySheet.java:92)
	at thinwire.apps.formcreator.PropertySheet.access$2(PropertySheet.java:90)
	at thinwire.apps.formcreator.PropertySheet$4.eventOccured(PropertySheet.java:76)
	at thinwire.apps.formcreator.MessageBus.fireEvent(MessageBus.java:101)
	at thinwire.apps.formcreator.MessageBus.fireEvent(MessageBus.java:92)
	at thinwire.apps.formcreator.ProjectSheet$1.propertyChange(ProjectSheet.java:411)
	at thinwire.ui.EventListenerImpl.fireEvent(EventListenerImpl.java:310)
	at thinwire.ui.EventListenerImpl.firePropertyChange(EventListenerImpl.java:231)
	at thinwire.ui.AbstractComponent.firePropertyChange(AbstractComponent.java:135)
	at thinwire.ui.Tree$Item.setSelected(Tree.java:189)
	at thinwire.render.web.TreeRenderer.itemChange(TreeRenderer.java:124)
	at thinwire.ui.EventListenerImpl.fireEvent(EventListenerImpl.java:312)
	at thinwire.ui.EventListenerImpl.fireItemChange(EventListenerImpl.java:286)
	at thinwire.ui.AbstractHierarchyComponent$ChildList.add(AbstractHierarchyComponent.java:58)
	at thinwire.ui.AbstractHierarchyComponent$ChildList.add(AbstractHierarchyComponent.java:44)
	at java.util.AbstractList.add(AbstractList.java:108)
	at thinwire.apps.formcreator.ProjectSheet.setActiveProject(ProjectSheet.java:465)
	at thinwire.apps.formcreator.ProjectSheet.access$3(ProjectSheet.java:437)
	at thinwire.apps.formcreator.ProjectSheet$4.eventOccured(ProjectSheet.java:73)
	at thinwire.apps.formcreator.MessageBus.fireEvent(MessageBus.java:101)
	at thinwire.apps.formcreator.Main.<init>(Main.java:255)
	at thinwire.apps.formcreator.Main.main(Main.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at thinwire.render.web.ApplicationEventListener.componentChange(ApplicationEventListener.java:117)
	at thinwire.render.web.EventProcessor.processUserActionEvent(EventProcessor.java:132)
	at thinwire.render.web.EventProcessor.run(EventProcessor.java:88)

Please helpe me

tanks

**Comment by tedchoward** [comment]
I'm sorry that the form creator isn't working, but I'm not surprised. We never finished it when we were active on the project. Except for the superficial work I did 4 years ago to make it build, the code hasn't been looked at in 10 years. I didn't really work back then either.

**Comment by cbsistem** [comment]
What development technology do you use now? Could you talk?
